# -*- coding: utf-8 -*-
"""GPA and Study Hours Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/gpa-and-study-hours-analysis-00593ec5-5374-43e3-8671-ab02ac1459e5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240228/auto/storage/goog4_request%26X-Goog-Date%3D20240228T201646Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D8cf68bbc057e404f6669db34fc82165743359de5bc29ab6778ae59194245161711f1be7d0c912641f92657e36e4b079fc55ce44a90b07ff3d1c54e04db5ade1b93c0886f6afd0745181d62adfa2efe1a776b2876780294cb403d1b9d01a44c2f7fb5b06cae18a6a45b60ddad3620ce42aaa9fdc09a4e2b1a84afe4ef6948d0d0ded96bd92d7b13b9769f4786eb4e48835163b41ebb64efab294761ec97bb3501d0052fefbff4ad30423bff67fb6e98d7b828eaa9ce1396255590877933e6590ff39def432cbda430a85d0c74f9e60009ef8a0ad6b385e61c1cfa2951da79c4576b4ea23c057207650150553ec0131c6d88c276bc7213f08155e3fdc5331a8f39

## 1. Importing Libraries and Loading Data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
data = pd.read_csv('/content/student_data (2).csv')

print(data.head())
print(data.info())

"""### Descriptive Statistics"""

print(data.describe())

"""### Data Visualization"""

# Histogram of GPA
plt.figure(figsize=(10, 6))
sns.histplot(data['gpa'], bins=20, kde=True)
plt.title('Distribution of GPA')
plt.xlabel('GPA')
plt.ylabel('Frequency')
plt.show()

# Scatter plot of GPA vs. Study Hours
plt.figure(figsize=(10, 6))
sns.scatterplot(data=data, x='study_hours', y='gpa')
plt.title('GPA vs. self esteem')
plt.xlabel('self esteem')
plt.ylabel('GPA')
plt.show()

print(data.isnull().sum())

# Box plot of Study Hours
plt.figure(figsize=(8, 5))
sns.boxplot(data['study_hours'])
plt.title('Box Plot of selfesteem')
plt.xlabel('Self_esteem')
plt.show()

# Remove outliers using IQR method
Q1 = data['study_hours'].quantile(0.25)
Q3 = data['study_hours'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
data = data[(data['study_hours'] >= lower_bound) & (data['study_hours'] <= upper_bound)]

correlation_matrix = data.corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

sns.lmplot(data=data, x='study_hours', y='gpa')
plt.title('GPA vs. Self_esteem (Regression)')
plt.xlabel('Self_esteem')
plt.ylabel('GPA')
plt.show()

plt.figure(figsize=(12, 6))
sns.kdeplot(data['gpa'], label='GPA')
sns.kdeplot(data['study_hours'], label='Self_esteem')
plt.title('Distribution of GPA and Self_esteem')
plt.xlabel('Values')
plt.ylabel('Density')
plt.legend()
plt.show()

"""## 5. Conclusion

In this analysis, we explored a dataset containing GPA and study hours data to uncover insights about the relationship between these two variables. Through a series of data exploration, visualization, and analysis techniques, we gained valuable insights into the dataset.

Key Findings:
- We observed a moderate positive correlation between study hours and GPA, indicating that students who study more tend to have higher GPAs.
- The scatter plot and regression line revealed a general trend where as study hours increase, GPA also tends to increase.
- The distribution plots showcased that the majority of students have GPAs clustered around certain values and follow a relatively normal distribution.

Data preprocessing played a crucial role in ensuring the quality of our analysis. We addressed missing values and outliers, which could have potentially skewed our results. Additionally, exploratory data analysis provided a comprehensive overview of the dataset's characteristics.

This analysis can provide valuable insights for both students and educators. Students can gain an understanding of the potential impact of their study habits on their academic performance, while educators can use these insights to tailor teaching strategies and support mechanisms.

As a next step, further investigation could be conducted to explore other potential factors influencing GPA, such as extracurricular activities, sleep patterns, or stress levels. Additionally, predictive modeling techniques could be employed to build models that predict GPA based on study hours and other relevant features.

In conclusion, the analysis highlights the positive relationship between study hours and GPA, shedding light on the importance of effective time management and dedication to academic success. This understanding can serve as a valuable tool for students aiming to enhance their academic performance and for educators seeking to optimize their teaching strategies.

Thank you for joining us on this exploration of GPA and study hours data!
"""